### ISSUE TITLE
Need option examples

### ISSUE THREAD

**Issue by sharmashivanand** [Suraj-Yadav/vscode-PHP-Formatter#1]
`php_beautifier --help`

The output is not compatible with   `"phpFormatter.php_beautifier.options": [],`

Kindly share some examples so that this extension becomes usable. Many thanks.

**Comment by Suraj-Yadav** [comment]
Sorry, but I stopped working on PHP long back. From what I remember you have to pass the exact arguments you would pass to `php_beautifier`, but I am not sure. 
Currently I even don't have PHP installed on my system so cannot confirm this.
